In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib 
matplotlib.rcParams["figure.figsize"] = (20,10)

import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

In [3]:
df1 = pd.read_csv("combined_appraisals.csv")
df1.head()

,orderID,subject_address,subject_subject_city_province_zip,subject_effective_date,subject_municipality_district,subject_site_dimensions,subject_lot_size_sf,subject_units_sq_ft,subject_year_built,subject_structure_type,...,property_year_built,property_roof,property_basement,property_cooling,property_heating,property_close_price,property_close_date,property_public_remarks,property_latitude,property_longitude
0,4762597,142-950 Oakview Ave Kingston ON K7M 6W8,"""Twin Oak Meadows""",Apr/11/2025,Kingston,Condo Common Property,NaN,SqFt,1976,Townhouse,...,NaN,NaN,Unfinished,Central Air,Forced Air,674000.0,2025-01-13,Welcome to this beautifully maintained and spa...,44.2325,-76.5901
1,4762597,142-950 Oakview Ave Kingston ON K7M 6W8,"""Twin Oak Meadows""",Apr/11/2025,Kingston,Condo Common Property,NaN,SqFt,1976,Townhouse,...,NaN,NaN,Unfinished,Central Air,Forced Air,674000.0,2025-01-13,Welcome to this beautifully maintained and spa...,44.2325,-76.5901
2,4762597,142-950 Oakview Ave Kingston ON K7M 6W8,"""Twin Oak Meadows""",Apr/11/2025,Kingston,Condo Common Property,NaN,SqFt,1976,Townhouse,...,NaN,NaN,Fin W/O,Central Air,Forced Air,585000.0,2025-01-14,"Come and see what this fully finished, Barr co...",44.2622,-76.5904
3,4762597,142-950 Oakview Ave Kingston ON K7M 6W8,"""Twin Oak Meadows""",Apr/11/2025,Kingston,Condo Common Property,NaN,SqFt,1976,Townhouse,...,NaN,NaN,Finished with Walk-Out,Central Air,Forced Air,585000.0,2025-01-14,"Come and see what this fully finished, Barr co...",44.2622,-76.5904
4,4762597,142-950 Oakview Ave Kingston ON K7M 6W8,"""Twin Oak Meadows""",Apr/11/2025,Kingston,Condo Common Property,NaN,SqFt,1976,Townhouse,...,NaN,NaN,"Part Bsmt, Unfinished",NaN,Baseboard,685000.0,2025-01-15,"Current valuation for 4056 Bath Rd, South of T...",44.2407,-76.6102

In [20]:

mask = df1['subject_year_built'].astype(str).str.fullmatch(r'\d{4}')
df_years = df1[mask].copy()

# 2. Convert year to int
df_years['subject_year_built'] = df_years['subject_year_built'].astype(int)

# 3. Subtract from 2025 to get the age
df_years['age'] = 2025 - df_years['subject_year_built']
df_years['age'].unique()

array([ 49,  14,  42,  47,  40,  84,   4,  19,   6,   1,  25,  43,  15,
        23,  57, 135,  32,   9,  73,   7,   8,  74,  17,  12,  21,  22,
        53, 180,  30,  64,  55, 115,   0,  85,  36, 140, 125,  51,   3,
        35,  10,  27,  50,  18,  75,  37,  54,  33,  26,  46,  48, 105])

In [23]:
df2 = df_years.copy()

keep_columns = [
    # Location information
    'property_city', 'property_province', 'property_postal_code',
    'property_latitude', 'property_longitude',
    
    # Property characteristics 
    'property_bedrooms', 'property_gla', 'property_full_baths', 'property_half_baths',
    'property_room_count', 'property_lot_size_sf', 'property_year_built',
    'property_property_sub_type', 'property_structure_type', 'property_levels',
    'property_basement', 'property_cooling', 'property_heating','subject_subject_age','comp_stories','age',
    
    # Target variable
    'property_close_price', 'property_close_date'
]

# Filter to keep only the columns we want
df2 = df2[keep_columns]
df2.head()

,property_city,property_province,property_postal_code,property_latitude,property_longitude,property_bedrooms,property_gla,property_full_baths,property_half_baths,property_room_count,...,property_structure_type,property_levels,property_basement,property_cooling,property_heating,subject_subject_age,comp_stories,age,property_close_price,property_close_date
0,Kingston,Ontario,K7M 9C8,44.2325,-76.5901,3.0,1500.0,3.0,NaN,11.0,...,Detached,Two,Unfinished,Central Air,Forced Air,49,2 Storey,49,674000.0,2025-01-13
1,Kingston,Ontario,K7M 9C8,44.2325,-76.5901,3.0,1750.0,NaN,NaN,11.0,...,"Detached, 2-Storey",2-Storey,Unfinished,Central Air,Forced Air,49,2 Storey,49,674000.0,2025-01-13
2,Kingston,Ontario,K7P 0K8,44.2622,-76.5904,3.0,1500.0,4.0,NaN,11.0,...,Freehold Townhouse,Two,Fin W/O,Central Air,Forced Air,49,2 Storey,49,585000.0,2025-01-14
3,Kingston,Ontario,K7P 0K8,44.2622,-76.5904,3.0,1300.0,NaN,NaN,11.0,...,"Freehold Townhouse, 2-Storey",2-Storey,Finished with Walk-Out,Central Air,Forced Air,49,2 Storey,49,585000.0,2025-01-14
4,Kingston,Ontario,K7M 4Y4,44.2407,-76.6102,4.0,NaN,4.0,0.0,13.0,...,Rural Resid,NaN,"Part Bsmt, Unfinished",NaN,Baseboard,49,2 Storey,49,685000.0,2025-01-15

In [27]:

always_keep_and_fill_zero = [
    'property_half_baths',
    'property_lot_size_sf',
    'property_basement',
    'property_full_baths'
]

total_rows = len(df2)
null_percentage = df2.isnull().sum() / total_rows * 100

columns_to_keep = set(null_percentage[null_percentage <= 10].index) | set(always_keep_and_fill_zero)
df3 = df2[list(columns_to_keep)].copy()

for col in always_keep_and_fill_zero:
    if col in df3.columns:
        df3[col] = df3[col].fillna(0)

removed_columns = set(null_percentage[null_percentage > 10].index) - set(always_keep_and_fill_zero)
print("\nRemoved columns:")
for col in removed_columns:
    print(f"- {col} ({null_percentage[col]:.2f}% null)")

print("\nNot Removed columns:")
for col in columns_to_keep:
    print(f"- {col} ({null_percentage[col]:.2f}% null)")
    # i replaced property_year_built with age so its okay

Removed columns:
- property_cooling (34.65% null)
- property_year_built (37.41% null)

Not Removed columns:
- property_postal_code (0.25% null)
- property_longitude (0.00% null)
- property_property_sub_type (0.74% null)
- property_basement (34.93% null)
- property_province (0.00% null)
- property_latitude (0.00% null)
- property_gla (1.72% null)
- property_city (0.03% null)
- property_bedrooms (1.89% null)
- property_full_baths (31.88% null)
- property_lot_size_sf (49.38% null)
- property_heating (1.82% null)
- property_room_count (1.49% null)
- comp_stories (0.00% null)
- subject_subject_age (0.00% null)
- property_levels (2.17% null)
- property_half_baths (61.52% null)
- property_close_price (0.79% null)
- property_structure_type (0.34% null)
- age (0.00% null)
- property_close_date (0.00% null)

In [28]:
df3.isnull().sum()

property_postal_code           69
property_longitude              0
property_property_sub_type    201
property_basement               0
property_province               0
property_latitude               0
property_gla                  468
property_city                   9
property_bedrooms             513
property_full_baths             0
property_lot_size_sf            0
property_heating              495
property_room_count           405
comp_stories                    0
subject_subject_age             0
property_levels               591
property_half_baths             0
property_close_price          216
property_structure_type        93
age                             0
property_close_date             0
dtype: int64

In [29]:
df3.head()

,property_postal_code,property_longitude,property_property_sub_type,property_basement,property_province,property_latitude,property_gla,property_city,property_bedrooms,property_full_baths,...,property_heating,property_room_count,comp_stories,subject_subject_age,property_levels,property_half_baths,property_close_price,property_structure_type,age,property_close_date
0,K7M 9C8,-76.5901,Detached,Unfinished,Ontario,44.2325,1500.0,Kingston,3.0,3.0,...,Forced Air,11.0,2 Storey,49,Two,0.0,674000.0,Detached,49,2025-01-13
1,K7M 9C8,-76.5901,Detached,Unfinished,Ontario,44.2325,1750.0,Kingston,3.0,0.0,...,Forced Air,11.0,2 Storey,49,2-Storey,0.0,674000.0,"Detached, 2-Storey",49,2025-01-13
2,K7P 0K8,-76.5904,Freehold Townhouse,Fin W/O,Ontario,44.2622,1500.0,Kingston,3.0,4.0,...,Forced Air,11.0,2 Storey,49,Two,0.0,585000.0,Freehold Townhouse,49,2025-01-14
3,K7P 0K8,-76.5904,Freehold Townhouse,Finished with Walk-Out,Ontario,44.2622,1300.0,Kingston,3.0,0.0,...,Forced Air,11.0,2 Storey,49,2-Storey,0.0,585000.0,"Freehold Townhouse, 2-Storey",49,2025-01-14
4,K7M 4Y4,-76.6102,Rural Resid,"Part Bsmt, Unfinished",Ontario,44.2407,NaN,Kingston,4.0,4.0,...,Baseboard,13.0,2 Storey,49,NaN,0.0,685000.0,Rural Resid,49,2025-01-15

In [30]:
df4 = df3.copy()
df4['price_per_sqft'] = df4['property_close_price']/df3['property_gla']
df4.head()

,property_postal_code,property_longitude,property_property_sub_type,property_basement,property_province,property_latitude,property_gla,property_city,property_bedrooms,property_full_baths,...,property_room_count,comp_stories,subject_subject_age,property_levels,property_half_baths,property_close_price,property_structure_type,age,property_close_date,price_per_sqft
0,K7M 9C8,-76.5901,Detached,Unfinished,Ontario,44.2325,1500.0,Kingston,3.0,3.0,...,11.0,2 Storey,49,Two,0.0,674000.0,Detached,49,2025-01-13,449.333333
1,K7M 9C8,-76.5901,Detached,Unfinished,Ontario,44.2325,1750.0,Kingston,3.0,0.0,...,11.0,2 Storey,49,2-Storey,0.0,674000.0,"Detached, 2-Storey",49,2025-01-13,385.142857
2,K7P 0K8,-76.5904,Freehold Townhouse,Fin W/O,Ontario,44.2622,1500.0,Kingston,3.0,4.0,...,11.0,2 Storey,49,Two,0.0,585000.0,Freehold Townhouse,49,2025-01-14,390.000000
3,K7P 0K8,-76.5904,Freehold Townhouse,Finished with Walk-Out,Ontario,44.2622,1300.0,Kingston,3.0,0.0,...,11.0,2 Storey,49,2-Storey,0.0,585000.0,"Freehold Townhouse, 2-Storey",49,2025-01-14,450.000000
4,K7M 4Y4,-76.6102,Rural Resid,"Part Bsmt, Unfinished",Ontario,44.2407,NaN,Kingston,4.0,4.0,...,13.0,2 Storey,49,NaN,0.0,685000.0,Rural Resid,49,2025-01-15,NaN

In [31]:
df4['property_structure_type'].unique()

array(['Detached', 'Detached, 2-Storey ', 'Freehold Townhouse',
       'Freehold Townhouse, 2-Storey ', 'Rural Resid',
       'Detached, Sidesplit 3 ', 'Detached, Sidesplit 4 ',
       'Detached, Bungalow ', 'Apartment', 'Condo Apartment, Apartment ',
       'Detached, Bungalow-Raised ', 'Semi-Detached',
       'Semi-Detached, 2-Storey ', 'Condo Townhouse, 2-Storey ',
       'Single Family Residence, Sidesplit ', 'Detached, Backsplit 4 ',
       'Condo Apt', 'Condo Townhouse', 'Detached, Backsplit 3 ',
       'Semi-Detached, Bungalow ', 'Semi-Detached, Bungalow-Raised ',
       'Condo Apartment, Bachelor/Studio ', 'Condo Townhouse, 3-Storey ',
       nan, 'Semi-Detached, Backsplit 3 ', 'Condo Apartment, 2-Storey ',
       'Detached, Sidesplit ', 'Common Element Condo, Apartment ',
       'Detached, 1 1/2 Storey ', 'Detached, Other ', 'Duplex, Bungalow ',
       'Single Family', 'Duplex', 'Row/Townhouse, Two Story ',
       'Single Family Residence, Two Story ',
       'Single Family Residence, 3 Storey ',
       'Row/Townhouse, Stacked Townhouse ',
       'Single Family Residence, Backsplit ', 'Row/Townhouse, 3 Storey ',
       'Detached, Single Family Residence, Bungalow ',
       'Row/Townhouse, Bungalow ', 'Single Family Residence, Bungalow ',
       'Freehold Townhouse, 3-Storey ',
       'Semi Detached, Single Family Residence, Bungalow ',
       'Freehold Townhouse, Bungalow ',
       'Single Family Residence, 1.5 Storey ', 'Detached, Bungaloft ',
       'Condo/Apt Unit, Two Story ',
       'Single Family Residence, 2.5 Storey ',
       'Condo Townhouse, Stacked Townhouse ',
       'Semi Detached, Single Family Residence, Two Story ',
       'Condo/Apt Unit, 1 Storey/Apt ',
       'Single Family Residence, Bungalow Raised ', 'Link, 2-Storey ',
       'Condo Townhouse, 1 Storey/Apt ', 'Other, 2-Storey ',
       'Condo Townhouse, Bungalow ', 'Condominium', 'Triplex',
       'Condo Apt, Apartment ', 'Detached, 3-Storey ',
       'Row Unit, 3 Storey, 3 Storey ', 'MobileTrailer, Bungalow ',
       'Fourplex', 'Semi Detached (Half Duplex)', 'Row/Townhouse',
       'Residential Land', 'Stacked Townhse', 'Stacked, 2 Storey ',
       'Condo Apartment, 3-Storey ', 'Row Unit, 2 Storey, 2 Storey ',
       'Condo Townhouse, Other ', 'Condo Townhouse, Apartment ',
       'Vacant Land ', 'Condo Townhouse, Bungaloft ',
       'Semi-Detached, 1 1/2 Storey ',
       'Freehold Townhouse, 2 1/2 Storey ', 'Multiplex',
       'Detached, 2 1/2 Storey ', 'Semi-Detached, 2 1/2 Storey ',
       'Multiplex, 3-Storey ', 'Link, 2 1/2 Storey ', 'Duplex, 2-Storey ',
       'Duplex, 3-Storey ', 'Condo Townhouse, Multi-Level ', '4 plex',
       'Detached Single Family', 'Residential', 'Link', 'Row Unit',
       'Condo Apartment, 1 Storey/Apt ', 'Full Duplex', 'Mobile',
       'Condo Apartment, Loft ', 'Condo Apartment, Multi-Level ',
       'Condo Apt, Loft ', 'Condo Apartment, Other ',
       'Semi-Detached, 3-Storey ', 'Locker ',
       'Rural Residential, Bungalow-Raised ',
       'Common Element Condo, Loft ',
       'Condo Apartment, Stacked Townhouse ', 'Detached, 2 Storey ',
       'Detached, Single Family Residence, Two Story ',
       'Semi-Detached, Backsplit 4 ', 'Multiplex, 1 1/2 Storey ',
       'Triplex, 2-Storey ', 'Fourplex, 2-Storey ',
       'Triplex, 1 1/2 Storey ', 'Detached, Backsplit 5 ',
       'Detached, Freehold, 2 Storey ',
       'Semi Detached, Single Family Residence, Bungalow Raised ',
       'Detached, 1 Storey/Apt ', 'Single Family Residence, Split Level ',
       'Single Family Residence ', 'Detached, Agriculture, Bungalow ',
       'Mobile Home, Mobile ', 'Row/Townhouse, Split Level ',
       'Semi Detached, Single Family Residence, Backsplit ',
       'Detached, Single Family Residence, Backsplit ',
       'Row/Townhouse, Bungalow Raised ', 'Row/Townhouse, Backsplit ',
       'Single Family Residence', 'Farm, 2-Storey '], dtype=object)

In [32]:
df5= df4[df4['property_structure_type'].str.contains('house', case=False, na=False)]
df5['property_structure_type'].unique()

array(['Freehold Townhouse', 'Freehold Townhouse, 2-Storey ',
       'Condo Townhouse, 2-Storey ', 'Condo Townhouse',
       'Condo Townhouse, 3-Storey ', 'Row/Townhouse, Two Story ',
       'Row/Townhouse, Stacked Townhouse ', 'Row/Townhouse, 3 Storey ',
       'Row/Townhouse, Bungalow ', 'Freehold Townhouse, 3-Storey ',
       'Freehold Townhouse, Bungalow ',
       'Condo Townhouse, Stacked Townhouse ',
       'Condo Townhouse, 1 Storey/Apt ', 'Condo Townhouse, Bungalow ',
       'Row/Townhouse', 'Condo Townhouse, Other ',
       'Condo Townhouse, Apartment ', 'Condo Townhouse, Bungaloft ',
       'Freehold Townhouse, 2 1/2 Storey ',
       'Condo Townhouse, Multi-Level ',
       'Condo Apartment, Stacked Townhouse ',
       'Row/Townhouse, Split Level ', 'Row/Townhouse, Bungalow Raised ',
       'Row/Townhouse, Backsplit '], dtype=object)

In [33]:
df5.shape

(4443, 22)

In [34]:
df5.head()

,property_postal_code,property_longitude,property_property_sub_type,property_basement,property_province,property_latitude,property_gla,property_city,property_bedrooms,property_full_baths,...,property_room_count,comp_stories,subject_subject_age,property_levels,property_half_baths,property_close_price,property_structure_type,age,property_close_date,price_per_sqft
2,K7P 0K8,-76.5904,Freehold Townhouse,Fin W/O,Ontario,44.2622,1500.0,Kingston,3.0,4.0,...,11.0,2 Storey,49,Two,0.0,585000.0,Freehold Townhouse,49,2025-01-14,390.000000
3,K7P 0K8,-76.5904,Freehold Townhouse,Finished with Walk-Out,Ontario,44.2622,1300.0,Kingston,3.0,0.0,...,11.0,2 Storey,49,2-Storey,0.0,585000.0,"Freehold Townhouse, 2-Storey",49,2025-01-14,450.000000
13,K7P 0M5,-76.5911,Freehold Townhouse,"Finished, Full",Ontario,44.2661,1550.0,Kingston,3.0,3.0,...,9.0,2 Storey,49,Two,0.0,572999.0,Freehold Townhouse,49,2025-01-24,369.676774
15,K7P 0M5,-76.5911,Freehold Townhouse,"Finished, Full",Ontario,44.2661,1564.0,Kingston,3.0,0.0,...,9.0,2 Storey,49,2-Storey,0.0,572999.0,"Freehold Townhouse, 2-Storey",49,2025-01-24,366.367647
28,K7M 7R6,-76.5903,Condo Townhouse,Unfinished,Ontario,44.2500,1100.0,Kingston,3.0,0.0,...,8.0,2 Storey,49,2-Storey,0.0,375000.0,"Condo Townhouse, 2-Storey",49,2025-01-31,340.909091

In [35]:
df5.dropna(inplace=True)

In [36]:
df5.shape

(4110, 22)

In [37]:
from fractions import Fraction
import re
import pandas as pd

def parse_storeys(s):

    if not isinstance(s, str):
        return pd.NA

    # look for "2 1/2" or "1.5" or "2"
    m = re.search(r'(\d+\s+\d+/\d+|\d+(\.\d+)?)', s)
    if not m:
        return pd.NA

    token = m.group(1)
    # if it’s “2 1/2” style, split and build via Fraction
    if ' ' in token and '/' in token:
        whole, frac = token.split()
        return float(int(whole) + Fraction(frac))
    return float(token)

# apply and cast to pandas’ nullable FloatDtype
df5['num_storeys'] = df5['comp_stories'].apply(parse_storeys).astype('Float64')

# now drop non-numeric rows
df5 = df5.dropna(subset=['num_storeys'])

# inspect the result
print(df5['num_storeys'].unique())

<FloatingArray>
[2.0, 2.5, 1.5, 1.0, 3.0, 4.0]
Length: 6, dtype: Float64

In [38]:
df5.head()

,property_postal_code,property_longitude,property_property_sub_type,property_basement,property_province,property_latitude,property_gla,property_city,property_bedrooms,property_full_baths,...,comp_stories,subject_subject_age,property_levels,property_half_baths,property_close_price,property_structure_type,age,property_close_date,price_per_sqft,num_storeys
2,K7P 0K8,-76.5904,Freehold Townhouse,Fin W/O,Ontario,44.2622,1500.0,Kingston,3.0,4.0,...,2 Storey,49,Two,0.0,585000.0,Freehold Townhouse,49,2025-01-14,390.000000,2.0
3,K7P 0K8,-76.5904,Freehold Townhouse,Finished with Walk-Out,Ontario,44.2622,1300.0,Kingston,3.0,0.0,...,2 Storey,49,2-Storey,0.0,585000.0,"Freehold Townhouse, 2-Storey",49,2025-01-14,450.000000,2.0
13,K7P 0M5,-76.5911,Freehold Townhouse,"Finished, Full",Ontario,44.2661,1550.0,Kingston,3.0,3.0,...,2 Storey,49,Two,0.0,572999.0,Freehold Townhouse,49,2025-01-24,369.676774,2.0
15,K7P 0M5,-76.5911,Freehold Townhouse,"Finished, Full",Ontario,44.2661,1564.0,Kingston,3.0,0.0,...,2 Storey,49,2-Storey,0.0,572999.0,"Freehold Townhouse, 2-Storey",49,2025-01-24,366.367647,2.0
28,K7M 7R6,-76.5903,Condo Townhouse,Unfinished,Ontario,44.2500,1100.0,Kingston,3.0,0.0,...,2 Storey,49,2-Storey,0.0,375000.0,"Condo Townhouse, 2-Storey",49,2025-01-31,340.909091,2.0

In [46]:
numeric_cols = df5.select_dtypes(include='number').columns
print(numeric_cols)

Index(['property_longitude', 'property_latitude', 'property_gla',
       'property_bedrooms', 'property_full_baths', 'property_lot_size_sf',
       'property_room_count', 'property_half_baths', 'property_close_price',
       'age', 'price_per_sqft', 'num_storeys', 'cluster'],
      dtype='object')

In [47]:
features = [
'property_longitude', 'property_latitude', 'property_gla',
       'property_bedrooms', 'property_full_baths', 'property_lot_size_sf',
       'property_room_count', 'property_half_baths', 'property_close_price',
       'age', 'price_per_sqft', 'num_storeys'
]

In [48]:
from sklearn.preprocessing import StandardScaler

X = df5[features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [49]:
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=10, random_state=42)
df5['cluster'] = kmeans.fit_predict(X_scaled)

In [52]:
from sklearn.metrics import pairwise_distances

def recommend_similar(df5, scaler, features, kmeans, query_idx, n=2):
    # 1) Get the query point’s cluster
    label = df5.loc[query_idx, 'cluster']

    # 2) Subset to that cluster
    same_cluster = df5[df5['cluster'] == label].copy()

    # 3) Compute scaled distances to the query property
    q_scaled = scaler.transform(df5.loc[[query_idx], features])
    S_scaled = scaler.transform(same_cluster[features])
    dists = pairwise_distances(q_scaled, S_scaled)[0]

    # 4) Attach distances and pick the closest n (excluding itself)
    same_cluster['dist'] = dists
    recs = (
        same_cluster
        .sort_values('dist')
        .drop(query_idx, errors='ignore')
        .head(n)
    )
    return recs

input_idx =43
# example: find 2 houses like the one at index=2 from df6 
recs = recommend_similar(df5, scaler, features, kmeans, query_idx=input_idx, n=4)
print(recs[['property_close_price', 'price_per_sqft', 'num_storeys', 'property_bedrooms','property_latitude',
    'property_longitude']])

     property_close_price  price_per_sqft  num_storeys  property_bedrooms  \
335              327000.0      297.272727          2.0                3.0
189              327000.0      297.272727          2.0                3.0
56               331000.0      254.615385          2.0                3.0
202              331000.0      254.615385          2.0                3.0

     property_latitude  property_longitude
335            44.2488            -76.5889
189            44.2488            -76.5889
56             44.2486            -76.5875
202            44.2486            -76.5875

In [45]:
df5.head(10)

,property_postal_code,property_longitude,property_property_sub_type,property_basement,property_province,property_latitude,property_gla,property_city,property_bedrooms,property_full_baths,...,subject_subject_age,property_levels,property_half_baths,property_close_price,property_structure_type,age,property_close_date,price_per_sqft,num_storeys,cluster
2,K7P 0K8,-76.5904,Freehold Townhouse,Fin W/O,Ontario,44.2622,1500.0,Kingston,3.0,4.0,...,49,Two,0.0,585000.0,Freehold Townhouse,49,2025-01-14,390.000000,2.0,2
3,K7P 0K8,-76.5904,Freehold Townhouse,Finished with Walk-Out,Ontario,44.2622,1300.0,Kingston,3.0,0.0,...,49,2-Storey,0.0,585000.0,"Freehold Townhouse, 2-Storey",49,2025-01-14,450.000000,2.0,2
13,K7P 0M5,-76.5911,Freehold Townhouse,"Finished, Full",Ontario,44.2661,1550.0,Kingston,3.0,3.0,...,49,Two,0.0,572999.0,Freehold Townhouse,49,2025-01-24,369.676774,2.0,0
15,K7P 0M5,-76.5911,Freehold Townhouse,"Finished, Full",Ontario,44.2661,1564.0,Kingston,3.0,0.0,...,49,2-Storey,0.0,572999.0,"Freehold Townhouse, 2-Storey",49,2025-01-24,366.367647,2.0,0
28,K7M 7R6,-76.5903,Condo Townhouse,Unfinished,Ontario,44.2500,1100.0,Kingston,3.0,0.0,...,49,2-Storey,0.0,375000.0,"Condo Townhouse, 2-Storey",49,2025-01-31,340.909091,2.0,6
43,K7M 6X7,-76.5889,Condo Townhouse,Finished,Ontario,44.2488,1100.0,Kingston,3.0,1.0,...,49,2-Storey,0.0,327000.0,Condo Townhouse,49,2025-02-05,297.272727,2.0,6
46,K7M 6X7,-76.5889,Condo Townhouse,Finished,Ontario,44.2488,1100.0,Kingston,3.0,0.0,...,49,2-Storey,0.0,327000.0,"Condo Townhouse, 2-Storey",49,2025-02-05,297.272727,2.0,6
56,K7M 6V6,-76.5875,Condo Townhouse,"Full, Unfinished",Ontario,44.2486,1300.0,Kingston,3.0,1.0,...,49,2-Storey,0.0,331000.0,Condo Townhouse,49,2025-02-13,254.615385,2.0,0
59,K7M 6V6,-76.5875,Condo Townhouse,"Full, Unfinished",Ontario,44.2486,1300.0,Kingston,3.0,0.0,...,49,2-Storey,0.0,331000.0,"Condo Townhouse, 2-Storey",49,2025-02-13,254.615385,2.0,0
60,K7M 6X6,-76.5892,Condo Townhouse,Part Fin,Ontario,44.2494,1100.0,Kingston,3.0,2.0,...,49,2-Storey,0.0,315000.0,Condo Townhouse,49,2025-02-14,286.363636,2.0,6